//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
        public string mecanico { get; set; }
        public Nullable<int> valor { get; set; }
        public Nullable<int> idFactura { get; set; }
        public Nullable<int> idTipoServicio { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual TipoServicio TipoServicio { get; set; }
    }
}
